### ISSUE TITLE
ERROR    shell.py:50 [Errno 98] Address already in use

### ISSUE THREAD

**Issue by ChaoqingXu** [qingshuisiyuan/electron-ssr-backup#43]
2019-10-10 15:35:46:408 [info] Register shortcut: toggleWindow, Ctrl+Shift+W
2019-10-10 15:35:47:257 [error] Unhandled Rejection at: Promise [object Promise], reason: SyntaxError: Unexpected token : in JSON at position 3
2019-10-10 15:35:48:202 [error] Unhandled Rejection at: Promise [object Promise], reason: SentryError: HTTP Error (429): Creation of this event was denied due to rate limiting
2019-10-10 15:35:48:203 [error] Unhandled Rejection at: Promise [object Promise], reason: SentryError: HTTP Error (429): Creation of this event was denied due to rate limiting
2019-10-10 15:35:53:634 [info] start download ssr
2019-10-10 15:37:51:435 [info] Register shortcut: toggleWindow, Ctrl+Shift+W
2019-10-10 15:37:51:481 [error] Unhandled Rejection at: Promise [object Promise], reason: SyntaxError: Unexpected token : in JSON at position 3
2019-10-10 15:37:52:066 [info] start download ssr
2019-10-10 15:37:53:000 [error] Unhandled Rejection at: Promise [object Promise], reason: SentryError: HTTP Error (429): Creation of this event was denied due to rate limiting
2019-10-10 15:37:53:000 [error] Unhandled Rejection at: Promise [object Promise], reason: SentryError: HTTP Error (429): Creation of this event was denied due to rate limiting
2019-10-10 15:38:13:565 [info] ssr download success
2019-10-10 15:42:51:990 [error] Error: listen EADDRINUSE 127.0.0.1:1080
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at Server.setupListenHandle [as _listen2] (net.js:1319:14)
    at listenInCluster (net.js:1367:12)
    at doListen (net.js:1493:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

2019-10-10 15:43:02:440 [info] run command: python /home/xcq/.config/electron-ssr/shadowsocksr/shadowsocks/local.py -s 185.199.224.181 -p 63024 -k ****** -m rc4-md5 -O origin -o plain -b 127.0.0.1 -l 1080
2019-10-10 15:43:02:456 [info] pac server listen at: 127.0.0.1:2333
2019-10-10 15:43:02:457 [info] http proxy server listen at: 127.0.0.1:12333
2019-10-10 15:43:02:644 [error] 2019-10-10 15:43:02 INFO     util.py:85 loading libcrypto from libcrypto.so.1.0.0
2019-10-10 15:43:02:644 [error] 2019-10-10 15:43:02 INFO     local.py:50 local start with protocol[origin] password [b'nFBUb8cm'] method [rc4-md5] obfs [plain] obfs_param []
2019-10-10 15:43:02 INFO     local.py:54 starting local at 127.0.0.1:1080
2019-10-10 15:43:02 INFO     asyncdns.py:324 dns server: [('127.0.1.1', 53)]
2019-10-10 15:43:02:648 [error] 2019-10-10 15:43:02 ERROR    shell.py:50 [Errno 98] Address already in use
2019-10-10 15:43:02:648 [info] IPv6 support

有没有大佬知道这啥情况啊．．．

**Comment by qingshuisiyuan** [comment]
你本地1080端口被占用你就换一个没有被占用的端口啊
软件默认使用1080端口
